### ISSUE TITLE
The Application doesn't work properly if Mac OS locale is right-to-left (rtl)

### ISSUE THREAD

**Issue by AmrIKhudair** [dwarvesf/hidden#103]
### Describe the bug

If Mac OS is right-to-left, the program simply doesn't work and goes really unexpected, even the expand/collapse icons are to the opposite direction that they should be.

### Steps to reproduce

1. Set your Mac OS system language to Arabic (or any other right-to-left language)
2. Log off and log in again (or restart)
3. Try to use the app and you will never be able to use it properly.

### Expected behaviour

That it works properly in right-to-left layouts

### Environment

 - OS: Mac OS 11.0.1 Big Sur
 - Version: latest

**Comment by viettrungphan** [comment]
Supported, please wait for the next release

**Comment by amrdoe** [comment]
Thanks so much!

**Comment by viettrungphan** [comment]
Would you like to help us translate the app to your language?

**Comment by amrdoe** [comment]
Yes sure, and Blurred.app also I use both in my daily life and am interested in seeing them both in Arabic.

**Comment by viettrungphan** [comment]
/* Class = "NSTextFieldCell"; title = "Settings"; ObjectID = "1Is-Ut-a9h"; */
"1Is-Ut-a9h.title" = "Settings";

/* Class = "NSMenuItem"; title = "Hidden Bar"; ObjectID = "1Xt-HY-uBw"; */
"1Xt-HY-uBw.title" = "Hidden Bar";

/* Class = "NSTextFieldCell"; title = "⭐️Always Hidden"; ObjectID = "1jU-1x-cFf"; */
"1jU-1x-cFf.title" = "⭐️Always Hidden";

/* Class = "NSTextFieldCell"; title = "Hidden Bar"; ObjectID = "2xp-Ht-xa6"; */
"2xp-Ht-xa6.title" = "Hidden Bar";

/* Class = "NSTextFieldCell"; title = "Version"; ObjectID = "4Au-5A-dYq"; */
"4Au-5A-dYq.title" = "Version";

/* Class = "NSMenuItem"; title = "Quit Hidden Bar"; ObjectID = "4sb-4s-VLi"; */
"4sb-4s-VLi.title" = "Quit Hidden Bar";

/* Class = "NSMenuItem"; title = "About Hidden Bar"; ObjectID = "5kV-Vb-QxS"; */
"5kV-Vb-QxS.title" = "About Hidden Bar";

/* Class = "NSButtonCell"; title = "Use the full MenuBar on expanding"; ObjectID = "8z8-6N-wnc"; */
"8z8-6N-wnc.title" = "Use the full MenuBar on expanding";

/* Class = "NSMenu"; title = "Main Menu"; ObjectID = "AYu-sK-qS6"; */
"AYu-sK-qS6.title" = "Main Menu";

/* Class = "NSSegmentedCell"; B2x-1Q-Aei.ibShadowedLabels[0] = "General"; ObjectID = "B2x-1Q-Aei"; */
"B2x-1Q-Aei.ibShadowedLabels[0]" = "General";

/* Class = "NSSegmentedCell"; B2x-1Q-Aei.ibShadowedLabels[1] = "About"; ObjectID = "B2x-1Q-Aei"; */
"B2x-1Q-Aei.ibShadowedLabels[1]" = "About";

/* Class = "NSMenuItem"; title = "Preferences…"; ObjectID = "BOF-NM-1cW"; */
"BOF-NM-1cW.title" = "Preferences…";

/* Class = "NSMenuItem"; title = "30 seconds"; ObjectID = "Ch6-Z2-LyX"; */
"Ch6-Z2-LyX.title" = "30 seconds";

/* Class = "NSTextFieldCell"; title = "Global Shortcut"; ObjectID = "HJP-Lf-rxm"; */
"HJP-Lf-rxm.title" = "Global Shortcut";

/* Class = "NSButtonCell"; title = "⌫"; ObjectID = "IId-1b-leb"; */
"IId-1b-leb.title" = "⌫";

/* Class = "NSBox"; title = "Box"; ObjectID = "Jjd-1G-63n"; */
"Jjd-1G-63n.title" = "Box";

/* Class = "NSMenuItem"; title = "Show All"; ObjectID = "Kd2-mp-pUS"; */
"Kd2-mp-pUS.title" = "Show All";

/* Class = "NSToolbarItem"; label = "Custom View"; ObjectID = "ML6-W4-U8X"; */
"ML6-W4-U8X.label" = "Custom View";

/* Class = "NSToolbarItem"; paletteLabel = "Custom View"; ObjectID = "ML6-W4-U8X"; */
"ML6-W4-U8X.paletteLabel" = "Custom View";

/* Class = "NSToolbarItem"; label = "Custom View"; ObjectID = "NIO-JJ-pjq"; */
"NIO-JJ-pjq.label" = "Custom View";

/* Class = "NSToolbarItem"; paletteLabel = "Custom View"; ObjectID = "NIO-JJ-pjq"; */
"NIO-JJ-pjq.paletteLabel" = "Custom View";

/* Class = "NSMenuItem"; title = "Services"; ObjectID = "NMo-om-nkz"; */
"NMo-om-nkz.title" = "Services";

/* Class = "NSButtonCell"; title = "Enable always hidden section"; ObjectID = "Nhn-ch-1f7"; */
"Nhn-ch-1f7.title" = "Enable always hidden section";

/* Class = "NSMenuItem"; title = "Hide Hidden Bar"; ObjectID = "Olw-nP-bQN"; */
"Olw-nP-bQN.title" = "Hide Hidden Bar";

/* Class = "NSTextFieldCell"; title = "Follow us on Twitter"; ObjectID = "Tba-C7-Zr8"; */
"Tba-C7-Zr8.title" = "Follow us on Twitter";

/* Class = "NSMenuItem"; title = "Hide Others"; ObjectID = "Vdr-fp-XzO"; */
"Vdr-fp-XzO.title" = "Hide Others";

/* Class = "NSButtonCell"; title = "Start Hidden Bar when I log in"; ObjectID = "W1G-55-zGo"; */
"W1G-55-zGo.title" = "Start Hidden Bar when I log in";

/* Class = "NSTextFieldCell"; title = "Menu bar cleaner"; ObjectID = "X4W-sr-Z32"; */
"X4W-sr-Z32.title" = "Menu bar cleaner";

/* Class = "NSTextFieldCell"; title = "Know more about us"; ObjectID = "Xb1-xM-sYy"; */
"Xb1-xM-sYy.title" = "Know more about us";

/* Class = "NSMenuItem"; title = "1 minute"; ObjectID = "Zkr-Xd-Ffh"; */
"Zkr-Xd-Ffh.title" = "1 minute";

/* Class = "NSTextFieldCell"; title = "MIT © Dwarves Foundation"; ObjectID = "b1t-QR-iSj"; */
"b1t-QR-iSj.title" = "MIT © Dwarves Foundation";

/* Class = "NSBox"; title = "Box"; ObjectID = "bFi-aV-ejJ"; */
"bFi-aV-ejJ.title" = "Box";

/* Class = "NSMenuItem"; title = "5 seconds"; ObjectID = "bzS-lm-JvT"; */
"bzS-lm-JvT.title" = "5 seconds";

/* Class = "NSTextFieldCell"; title = "Hidden"; ObjectID = "cXt-8R-PHo"; */
"cXt-8R-PHo.title" = "Hidden";

/* Class = "NSButtonCell"; title = "Set Shortcut"; ObjectID = "fc2-jD-QNf"; */
"fc2-jD-QNf.title" = "Set Shortcut";

/* Class = "NSTextFieldCell"; title = "This app is fully open source"; ObjectID = "fqc-io-QOP"; */
"fqc-io-QOP.title" = "This app is fully open source";

/* Class = "NSButtonCell"; title = "Show preferences on launch"; ObjectID = "hCh-Ue-NgH"; */
"hCh-Ue-NgH.title" = "Show preferences on launch";

/* Class = "NSMenu"; title = "Services"; ObjectID = "hz9-B4-Xy5"; */
"hz9-B4-Xy5.title" = "Services";

/* Class = "NSTextFieldCell"; title = "Shown"; ObjectID = "iyS-g5-5mk"; */
"iyS-g5-5mk.title" = "Shown";

/* Class = "NSTextFieldCell"; title = "In your Mac's menu bar, hold ⌘ and drag icons\nbetween sections to configure Hidden Bar."; ObjectID = "k7C-e5-6a0"; */
"k7C-e5-6a0.title" = "In your Mac's menu bar, hold ⌘ and drag icons\nbetween sections to configure Hidden Bar.";

/* Class = "NSButtonCell"; title = "Automatically hide icon after: "; ObjectID = "kg8-rW-srh"; */
"kg8-rW-srh.title" = "Automatically hide icon after: ";

/* Class = "NSBox"; title = "Box"; ObjectID = "mtL-vU-2iq"; */
"mtL-vU-2iq.title" = "Box";

/* Class = "NSMenuItem"; title = "15 seconds"; ObjectID = "rdn-Xm-fZD"; */
"rdn-Xm-fZD.title" = "15 seconds";

/* Class = "NSTextFieldCell"; title = "Email us"; ObjectID = "sRr-sO-uV0"; */
"sRr-sO-uV0.title" = "Email us";

/* Class = "NSMenu"; title = "Hidden Bar"; ObjectID = "uQy-DD-JDr"; */
"uQy-DD-JDr.title" = "Hidden Bar";

/* Class = "NSMenuItem"; title = "10 seconds"; ObjectID = "z2X-nw-vxX"; */
"z2X-nw-vxX.title" = "10 seconds";

/* Class = "NSTextFieldCell"; title = "Monday 08 Mar 9:00AM"; ObjectID = "zAH-cs-dar"; */
"zAH-cs-dar.title" = "Monday 08 Mar 9:00AM";

/* Class = "NSTextFieldCell"; title = "General"; ObjectID = "zAf-vj-OOZ"; */
"zAf-vj-OOZ.title" = "General";

///////////////////////////////////////////

"Preferences..." = "Preferences...";
"Toggle Auto Collapse" = "Toggle Auto Collapse";
"Enable Auto Collapse" = "Enable Auto Collapse";
"Disable Auto Collapse" = "Disable Auto Collapse";
"Quit" = "Quit";
"Set Shortcut" = "Set Shortcut";
"Tutorial text" = "
Use the always hidden feature to keep your icons tidy. Here's how to set it
Steps to enable:
1. Enable the always hidden “􀥤” (translucent color bar)
2. Hold  􀆔 and drag it on the left-hand side of the normal bar, then move any icons you want to disappear on the left of that bar.
3. Finally, please right-click on the collapse “􀆊” icon to make it disappear.
Steps to view always hidden icons:
1. You right-click on “􀆊” icon again to view and repeat the action to enable the feature. Enjoy 😉!
";

**Comment by viettrungphan** [comment]
@AmrIKhudair please help us Arabic language.
Keep the text on the left and translate on the right, for example Chinese:
"Set Shortcut" = "設定快捷鍵";

Thanks for your contribution.

**Comment by viettrungphan** [comment]
`/* Class = "NSMenu"; title = "Hidden Bar"; ObjectID = "uQy-DD-JDr"; */
`Something between` /*xxxxxx*/ `is note you dont need translate it.

**Comment by amrdoe** [comment]
/* Class = "NSTextFieldCell"; title = "Settings"; ObjectID = "1Is-Ut-a9h"; */
"1Is-Ut-a9h.title" = "الإعدادات";

/* Class = "NSMenuItem"; title = "Hidden Bar"; ObjectID = "1Xt-HY-uBw"; */
"1Xt-HY-uBw.title" = "الشريط المخفي";

/* Class = "NSTextFieldCell"; title = "⭐️Always Hidden"; ObjectID = "1jU-1x-cFf"; */
"1jU-1x-cFf.title" = "⭐️مخفي دائما";

/* Class = "NSTextFieldCell"; title = "Hidden Bar"; ObjectID = "2xp-Ht-xa6"; */
"2xp-Ht-xa6.title" = "الشريط المخفي";

/* Class = "NSTextFieldCell"; title = "Version"; ObjectID = "4Au-5A-dYq"; */
"4Au-5A-dYq.title" = "الإصدار";

/* Class = "NSMenuItem"; title = "Quit Hidden Bar"; ObjectID = "4sb-4s-VLi"; */
"4sb-4s-VLi.title" = "إنهاء الشريط المخفي";

/* Class = "NSMenuItem"; title = "About Hidden Bar"; ObjectID = "5kV-Vb-QxS"; */
"5kV-Vb-QxS.title" = "حول الشريط المخفي";

/* Class = "NSButtonCell"; title = "Use the full MenuBar on expanding"; ObjectID = "8z8-6N-wnc"; */
"8z8-6N-wnc.title" = "استخدم كامل شريط القائمة عند التوسيع";

/* Class = "NSMenu"; title = "Main Menu"; ObjectID = "AYu-sK-qS6"; */
"AYu-sK-qS6.title" = "القائمة الرئيسية";

/* Class = "NSSegmentedCell"; B2x-1Q-Aei.ibShadowedLabels[0] = "General"; ObjectID = "B2x-1Q-Aei"; */
"B2x-1Q-Aei.ibShadowedLabels[0]" = "عام";

/* Class = "NSSegmentedCell"; B2x-1Q-Aei.ibShadowedLabels[1] = "About"; ObjectID = "B2x-1Q-Aei"; */
"B2x-1Q-Aei.ibShadowedLabels[1]" = "حول";

/* Class = "NSMenuItem"; title = "Preferences…"; ObjectID = "BOF-NM-1cW"; */
"BOF-NM-1cW.title" = "تفضيلات…";

/* Class = "NSMenuItem"; title = "30 seconds"; ObjectID = "Ch6-Z2-LyX"; */
"Ch6-Z2-LyX.title" = "٣٠ ثانية";

/* Class = "NSTextFieldCell"; title = "Global Shortcut"; ObjectID = "HJP-Lf-rxm"; */
"HJP-Lf-rxm.title" = "الاختصار المعمم";

/* Class = "NSButtonCell"; title = "⌫"; ObjectID = "IId-1b-leb"; */
"IId-1b-leb.title" = "⌫";

/* Class = "NSBox"; title = "Box"; ObjectID = "Jjd-1G-63n"; */
"Jjd-1G-63n.title" = "صندوق";

/* Class = "NSMenuItem"; title = "Show All"; ObjectID = "Kd2-mp-pUS"; */
"Kd2-mp-pUS.title" = "أظهر الكل";

/* Class = "NSToolbarItem"; label = "Custom View"; ObjectID = "ML6-W4-U8X"; */
"ML6-W4-U8X.label" = "عرض مخصص";

/* Class = "NSToolbarItem"; paletteLabel = "Custom View"; ObjectID = "ML6-W4-U8X"; */
"ML6-W4-U8X.paletteLabel" = "عرض مخصص";

/* Class = "NSToolbarItem"; label = "Custom View"; ObjectID = "NIO-JJ-pjq"; */
"NIO-JJ-pjq.label" = "عرض مخصص";

/* Class = "NSToolbarItem"; paletteLabel = "Custom View"; ObjectID = "NIO-JJ-pjq"; */
"NIO-JJ-pjq.paletteLabel" = "عرض مخصص";

/* Class = "NSMenuItem"; title = "Services"; ObjectID = "NMo-om-nkz"; */
"NMo-om-nkz.title" = "خدمات";

/* Class = "NSButtonCell"; title = "Enable always hidden section"; ObjectID = "Nhn-ch-1f7"; */
"Nhn-ch-1f7.title" = "تمكين القسم المخفي دائما";

/* Class = "NSMenuItem"; title = "Hide Hidden Bar"; ObjectID = "Olw-nP-bQN"; */
"Olw-nP-bQN.title" = "أخف الشريط المخفي";

/* Class = "NSTextFieldCell"; title = "Follow us on Twitter"; ObjectID = "Tba-C7-Zr8"; */
"Tba-C7-Zr8.title" = "تابعنا على تويتر";

/* Class = "NSMenuItem"; title = "Hide Others"; ObjectID = "Vdr-fp-XzO"; */
"Vdr-fp-XzO.title" = "أخف الآخرين";

/* Class = "NSButtonCell"; title = "Start Hidden Bar when I log in"; ObjectID = "W1G-55-zGo"; */
"W1G-55-zGo.title" = "شغل الشريط المخفي عندما أقوم بتسجيل الدخول";

/* Class = "NSTextFieldCell"; title = "Menu bar cleaner"; ObjectID = "X4W-sr-Z32"; */
"X4W-sr-Z32.title" = "منظف شريط القائمة";

/* Class = "NSTextFieldCell"; title = "Know more about us"; ObjectID = "Xb1-xM-sYy"; */
"Xb1-xM-sYy.title" = "إعرف المزيد عنا";

/* Class = "NSMenuItem"; title = "1 minute"; ObjectID = "Zkr-Xd-Ffh"; */
"Zkr-Xd-Ffh.title" = "دقيقة واحدة";

/* Class = "NSTextFieldCell"; title = "MIT © Dwarves Foundation"; ObjectID = "b1t-QR-iSj"; */
"b1t-QR-iSj.title" = "MIT © Dwarves Foundation";

/* Class = "NSBox"; title = "Box"; ObjectID = "bFi-aV-ejJ"; */
"bFi-aV-ejJ.title" = "صندوق";

/* Class = "NSMenuItem"; title = "5 seconds"; ObjectID = "bzS-lm-JvT"; */
"bzS-lm-JvT.title" = "٥ ثوان";

/* Class = "NSTextFieldCell"; title = "Hidden"; ObjectID = "cXt-8R-PHo"; */
"cXt-8R-PHo.title" = "مخفي";

/* Class = "NSButtonCell"; title = "Set Shortcut"; ObjectID = "fc2-jD-QNf"; */
"fc2-jD-QNf.title" = "عين اختصارا";

/* Class = "NSTextFieldCell"; title = "This app is fully open source"; ObjectID = "fqc-io-QOP"; */
"fqc-io-QOP.title" = "هذا التطبيق مفتوح المصدر بالكامل";

/* Class = "NSButtonCell"; title = "Show preferences on launch"; ObjectID = "hCh-Ue-NgH"; */
"hCh-Ue-NgH.title" = "إعرض التفضيلات عند بدء التشغيل";

/* Class = "NSMenu"; title = "Services"; ObjectID = "hz9-B4-Xy5"; */
"hz9-B4-Xy5.title" = "خدمات";

/* Class = "NSTextFieldCell"; title = "Shown"; ObjectID = "iyS-g5-5mk"; */
"iyS-g5-5mk.title" = "ظاهر";

/* Class = "NSTextFieldCell"; title = "In your Mac's menu bar, hold ⌘ and drag icons\nbetween sections to configure Hidden Bar."; ObjectID = "k7C-e5-6a0"; */
"k7C-e5-6a0.title" = "في شريط القائمة الخاص بـMac الخاص بك، استمر بالضغط على ⌘ واسحب الأيقونات\nبين الأقسام لتكوين الشريط المخفي.";

/* Class = "NSButtonCell"; title = "Automatically hide icon after: "; ObjectID = "kg8-rW-srh"; */
"kg8-rW-srh.title" = "أخف الأيقونة تلقائيا بعد: ";

/* Class = "NSBox"; title = "Box"; ObjectID = "mtL-vU-2iq"; */
"mtL-vU-2iq.title" = "صندوق";

/* Class = "NSMenuItem"; title = "15 seconds"; ObjectID = "rdn-Xm-fZD"; */
"rdn-Xm-fZD.title" = "١٥ ثانية";

/* Class = "NSTextFieldCell"; title = "Email us"; ObjectID = "sRr-sO-uV0"; */
"sRr-sO-uV0.title" = "راسلنا إلكنرونيا";

/* Class = "NSMenu"; title = "Hidden Bar"; ObjectID = "uQy-DD-JDr"; */
"uQy-DD-JDr.title" = "الشريط المخفي";

/* Class = "NSMenuItem"; title = "10 seconds"; ObjectID = "z2X-nw-vxX"; */
"z2X-nw-vxX.title" = "١٠ ثوان";

/* Class = "NSTextFieldCell"; title = "Monday 08 Mar 9:00AM"; ObjectID = "zAH-cs-dar"; */
"zAH-cs-dar.title" = "الإثنين ٠٨ مارس ٩:٠٠ صباحا";

/* Class = "NSTextFieldCell"; title = "General"; ObjectID = "zAf-vj-OOZ"; */
"zAf-vj-OOZ.title" = "عام";

///////////////////////////////////////////

"Preferences..." = "تفضيلات...";
"Toggle Auto Collapse" = "بدل حالة الطي التلقائي";
"Enable Auto Collapse" = "مكن الطي التلقائي";
"Disable Auto Collapse" = "عطل الطي التلقائي";
"Quit" = "إنهاء";
"Set Shortcut" = "عين اختصارا";
"Tutorial text" = "
استخدم ميزة مخفي دائما لتبقي أيقوناتك مرتبة. إليك كيفية تعيينها
خطوات التمكين:

مكن “􀥤” الخاص بمخفي دائما (شريط اللون الشفاف)
استمر بالضغط على 􀆔 واسحبه إلى الجانب الأيمن من الشريط العادي، ثم حرك أي أيقونات تريد إخفائها إلى يمين هذا الشريط.
أخيرا، فضلا أنقر بالزر الأيمن على أيقونة الطي “􀆊” لجعلها تختفي.
خطوات عرض الأيقونات المخفية دائما:
أنقر بالزر الأيمن على أيقونة “􀆊” ثاتية للعرض وكرر الإجراء لتمكين الميزة. استمتع 😉!
";

**Comment by viettrungphan** [comment]
Thank, I will email you when we have new feature for HiddenBar.

Regards!
Dwarves Foundation MacOS team.

**Comment by viettrungphan** [comment]
@AmrIKhudair I forget one thing, RTL language "Tutorial text" should describe translucent bar should be on the right-hand side of the collapse bar, I'm not sure you aware and make that change?

**Comment by amrdoe** [comment]
Yes I am aware of that and have inverted all directions in the text to those which correspond to the RTL layout

**Comment by amrdoe** [comment]
Hello there are minor typos in the translation I had fixed as edits on the same comment. Please consider merging these changes in the next release.
