### ISSUE TITLE
Big Sur style app icon

### ISSUE THREAD

**Issue by p-z-l** [dwarvesf/hidden#116]
While I'm working on the fancy mouse and menu detection thing, I think it's time to have a new app icon to match the overall design language of macOS Big Sur. Here is several candidates for the new rounded rectangle app icons, I'm not sure which one is better.

<img width="1030" alt="Screen Shot 2021-03-03 at 9 52 03 PM" src="https://user-images.githubusercontent.com/43706386/109815859-13c5b100-7c6b-11eb-9ce9-b17577d73968.png">

**Comment by viettrungphan** [comment]
woa, nice.

**Comment by bringastar** [comment]
Hello!

**Comment by viettrungphan** [comment]
Please create pull request, our designer really like it.

**Comment by p-z-l** [comment]
#118
