### ISSUE TITLE
feature request:Hover over the menu bar to reveal hidden icons

### ISSUE THREAD

**Issue by mortyhuang** [dwarvesf/hidden#117]
Hover over the menu bar to reveal hidden icons, or click on the menu bar to immediately access the hidden menu bar items.
![quickreveal](https://user-images.githubusercontent.com/47255125/109853071-754c4680-7c90-11eb-9dd6-a2fa1a266337.gif)
Features similar to Bartender 4

**Comment by viettrungphan** [comment]
#115
