### ISSUE TITLE
Hidden part never collapses

### ISSUE THREAD

**Issue by vatbub** [dwarvesf/hidden#122]
### Describe the bug

I set my menu bar up as shown in the screenshot.
However, clicking the hide button does nothing. I also set the hidden section to automatically collapse after 10 seconds, but it never collapses.

### Steps to reproduce

1. Open Hidden Bar
2. Put some icons in the hidden section
3. click the arrow button
4. The hidden section does not collapse

Alternatively:
1. Open Hidden Bar
2. Put some icons in the hidden section
3. Go into the settings and enable "Automatically hide icon after 10 seconds"
4. The hidden section never collapses

### Expected behaviour

The hidden section collapses when clicking the arrow button or after the 10 seconds have elapsed.

**Screenshots**

<img width="674" alt="Screenshot 2021-04-16 at 10 32 13" src="https://user-images.githubusercontent.com/13379225/114996365-0b35dc80-9e9f-11eb-8585-d6a096f782b3.png">

### Environment

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.2.3
 - App version 1.7 (11)

If it makes a difference: I have a second screen installed, but the issue arises no matter whether the second screen is connected or not.

Let me know if you need more information for debugging/troubleshooting :)

**Comment by lucky13820** [comment]
I think you need to move the arrow icon on the right side of the hidden icon. So the things you want to show are between your arrow icon and hidden icon, all the things on the left side of the hidden icon are hidden. 
![tutorial](https://user-images.githubusercontent.com/7293811/115782881-0b3b4e00-a371-11eb-8f07-4e111bd62c32.gif)

**Comment by vatbub** [comment]
Ah, thanks, that solved it 😎
