### ISSUE TITLE
My hidden icon is not showing on the menu bar so I can't hide any icons. 

### ISSUE THREAD

**Issue by lucky13820** [dwarvesf/hidden#124]
### Describe the bug

The hidden icon is not showing on the menu bar. It only shows an empty space and I can drag the empty space around. But it won't hide anything when I click the arrow icon. 

### Steps to reproduce

Download the app from Brew and open it

### Expected behaviour

I should see the hidden icon and all the icons on the left side of the hidden icon should be hideen when I click the arrow icon. 

**Screenshots**

<img width="598" alt="Screen Shot 2021-04-22 at 1 46 26 PM" src="https://user-images.githubusercontent.com/7293811/115783225-7127d580-a371-11eb-950d-d1a4c7436161.png">
 The empty space I circled is what I believe should be the hidden icon, but somehow it doesn't show up. 

### Environment

**Desktop (please complete the following information):**
 - OS: BigSur 11.2.3
 - MacBook Pro 13 2020

**Comment by viettrungphan** [comment]
<img width="686" alt="Screen Shot 2021-04-23 at 09 12 46" src="https://user-images.githubusercontent.com/35858359/115808119-12fffe80-a414-11eb-90e8-57b849191f8c.png">
I believe you in dark mode and has a very dark background color so it very hard to see the translucent bar.
One more thing is you have a lot of status bar icons, the normal bar | hidden at the very left-hand side by not enough space for it displays.
You can quick some app to make some free space for it to show up and drag it to the right (don't forget toggle the < icon to show it if necessary)
