### ISSUE TITLE
About the recognization of shortcut keys that user input

### ISSUE THREAD

**Issue by fanvinga** [dwarvesf/hidden#125]
### Describe the bug

In HiddenBar's preferences, we can easily set global shortcut keys to support expand and collapse operations. But for the recognization of shortcut keys that user input, Hiddenbar is different from the other software with similar functions

### Steps to reproduce

1. Go to `Preferences`
2. Click `Global Support` 
3. Enter `Control` and `Space` at the same time 
4. View the recognition of shortcut keys 
5. HiddenBar will recognize `Control+Space` as `^ (here's a blank)`

### Expected behaviour

HiddenBar should recognize functions keys as its name like this 
![image](https://user-images.githubusercontent.com/26292849/115982503-4e462d00-a5ce-11eb-920e-d192983a3018.jpeg)

**Screenshots**

![image](https://user-images.githubusercontent.com/26292849/115982532-82b9e900-a5ce-11eb-9f04-bdebb5666351.jpeg)

### Environment

**Desktop:**
 - OS: macOS 11.2.3
 - HiddenBar Version: 1.7

**Comment by viettrungphan** [comment]
Thanks for reporting the bug.

**Comment by viettrungphan** [comment]
Fix on the next release
