### ISSUE TITLE
Icon for macOS Big Sur

### ISSUE THREAD

**Issue by ya2s** [dwarvesf/hidden#127]
### Describe the bug
Are you planning to change to a square icon compatible with bigsur?

### Expected behaviour
I think hidden bar should also support the new icon design specifications
https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

**Comment by p-z-l** [comment]
The updated Big Sur style icon is already merged into the develop branch, I believe that it will be released in the next version
(#118)
