### ISSUE TITLE
Settings import/export

### ISSUE THREAD

**Issue by AlecRust** [dwarvesf/hidden#128]
Surprised I couldn't find an existing issue for this, feel free to close if this has been answered already.

Are there any plans for export/import of Hidden Bar settings as JSON or similar?

I install Hidden Bar via Homebrew Cask and would ideally like to keep the settings in my dotfiles so I don't have to configure it on a new Mac.

**Comment by viettrungphan** [comment]
I don't think it possible, the way the app working required the user to drag menu icons so the system statusbar can remember the position of those icons. It OS level, not the app itself.
