### ISSUE TITLE
Hidden Bar 1.8 can't open

### ISSUE THREAD

**Issue by AlecRust** [dwarvesf/hidden#139]
### Describe the bug

After installing Hidden Bar 1.8, the application cannot be opened.

Have tried installing via Homebrew cask, and manually.

### Expected behaviour

App opens.

**Screenshots**

![screenshot](https://i.imgur.com/q3eFKdx.png)

### Environment
 - OS: macOS 11.4

**Comment by viettrungphan** [comment]
@AlecRust  please try following this link:
https://www.macworld.com/article/228379/how-to-run-apps-that-are-not-from-the-app-store-in-macos-sierra.html

**Comment by AlecRust** [comment]
Thanks @viettrungphan after confirming the open in System Preferences > Security & Privacy this was able to open.

Is this a change in 1.8 perhaps? I don't remember having to do this when installing earlier versions.

**Comment by viettrungphan** [comment]
Since Mojave (as I remember) Apple improve securities to protect users from apps outside Appstore. The user using an unknown source at their own risk. In this cage we are open source, you can check the source or build your own app so don't worry 😉.
