### ISSUE TITLE
Always Hidden Mode Not Working

### ISSUE THREAD

**Issue by drewauff** [dwarvesf/hidden#140]
MacOS Catalina.
Hidden Bar 1.8(12)

1) Cannot access "always hidden" mode
2) Image in tutorial show which key to hit is broken.

**Comment by gingerbeardman** [comment]
Did you solve this?

**Comment by drewauff** [comment]
yeh thats why I closed it haha..seems the updater didn't finish (close and restart).

Appreciate the reply, Thank you.

**Comment by gingerbeardman** [comment]
I ask because I can't get it to work in the current version

**Comment by drewauff** [comment]
@gingerbeardman oh haha, somehow thought you were the dev..I didnt really like the implementation of the "always hidden" mode so I wen back to Dozer, works much better for me.

note: I am still using Hidden, just using their implementation of "always hidden" I feel Dozer does this a bit better.
