### ISSUE TITLE
Items to left of always hide item are not hidden

### ISSUE THREAD

**Issue by gingerbeardman** [dwarvesf/hidden#141]
### Describe the bug

Items to left of always hide item are not hidden

### Steps to reproduce

1. Switch on always hide feature
2. Position some items to left of always hide market
3. Right click hidden bar marker

### Expected behaviour

- far left items should be hidden

### Actual behaviour 

- all icons are shown

### Environment

You may write here the specifications like the version of the project, operating system, or hardware if applicable.

**Desktop (please complete the following information):**
 - OS: 11.4

**Comment by hanniballecter86** [comment]
I encountered  this issue as well.

**Comment by Muzosh** [comment]
In step 3, are you right-clicking the translucent bar or the > arrow? You are supposed to right click do arrow, not the bar

**Comment by gingerbeardman** [comment]
I was right clicking the arrow.

It's confusing to right click to show the always hidden items, as you have to remember to right click to hide them again. (alt+click is the same as right-click for this feature)

Anyway, I eventually seem to have it working. Not 100% sure what has changed, but happy to mark it up to user error in my case.

**Comment by fat4talk** [comment]
Restart the Application may help

**Comment by viettrungphan** [comment]
the right-click on the menu somehow hard to trigger than the left click. I also see this behavior during development (Using a trackpad).
