### ISSUE TITLE
unable to hide Siri icon

### ISSUE THREAD

**Issue by daaaaaaaaaniel** [dwarvesf/hidden#155]
### Describe the bug

I can't move the Siri menu bar icon because Siri gets triggers every time I try to move it.

### Steps to reproduce

When holding ⌘ and attempting to drag the Siri icon from its default position, clicking the icon triggers Siri.

### Expected behaviour

I want to hide the Siri icon inside the Hidden Bar section of the menu bar.

### Environment

Hidden Bar version 1.8 (12) on M1 MacBook Pro, macOS Big Sur 11.5

**Comment by viettrungphan** [comment]
That is the behavior of the new macOS, we can't do anything with it.
