### ISSUE TITLE
Feature I can Add: Preferences (cmd+,) opens app.

### ISSUE THREAD

**Issue by Mcrich23** [dwarvesf/hidden#160]
I would love to add to the app by making it so if click preferences of hidden bar, it opens the app with those controls.

Can I?

**Comment by viettrungphan** [comment]
This is a utility app, you just open that setting sometimes, one more thing the key combo using to open preferences only works when the target app is in active mode (have active and focus window) our app normally doesn't have any window, no way to focus to receive the key combo. When clicking on the app menu you can use hotkey Cmd+Shift+P to open is the second option
<img width="224" alt="Screen Shot 2021-08-24 at 12 21 22" src="https://user-images.githubusercontent.com/35858359/130560210-71aa6711-96f4-46e0-84ee-fda8cc869efc.png">
.
