### ISSUE TITLE
Always hidden section not working

### ISSUE THREAD

**Issue by CedricDeVijt** [dwarvesf/hidden#163]
I'm new to this program but I haven't been able to use the always hidden section. When I put the icons to the lest of the more translucent line and right click the arrow nothing happens except for both of the lines to disappear but the icons don't.

I'm currently on the macOS 12 beta but on the latest macOS 11 it didn't work either.

<img width="823" alt="Screenshot 2021-09-05 at 12 33 12" src="https://user-images.githubusercontent.com/46058254/132123825-e0de1181-ad69-4bab-ab07-fa12afd04b18.png">
<img width="753" alt="Screenshot 2021-09-05 at 12 33 32" src="https://user-images.githubusercontent.com/46058254/132123828-02e2efe6-b1b6-4034-8da3-a94146971fdc.png">

**Comment by viettrungphan** [comment]
Thanks for report the bug. We going to investigate it.

**Comment by CedricDeVijt** [comment]
After restarting my MacBook it the changes took place. So the setting worked only after restarting my MacBook.

**Comment by bnaman50** [comment]
Hey @viettrungphan , 

I think always hidden section is still not working. Could you please help me out.?

<img width="596" alt="image" src="https://user-images.githubusercontent.com/5251592/166562748-0bdbd628-df12-41a8-b286-001a91dd98f0.png">

Version - 1.9
MacOS - 10.14.6 (Mojave)

Thanks, 
Naman
