### ISSUE TITLE
Unable to move the arrow 

### ISSUE THREAD

**Issue by Daniel3356** [dwarvesf/hidden#166]
After downloading hidden bar from the app store, I am unable to move the arrow like this GIF: https://github.com/dwarvesf/hidden/blob/develop/img/tutorial.gif

How could I be able to make the arrow ?

**Comment by viettrungphan** [comment]
Hold Command key to move menu bar button. Some systems icons on the newest macOS can't move.

**Comment by Daniel3356** [comment]
Thanks It works
