### ISSUE TITLE
Not Bug- Suggestion: Use Command-comma for Preferences

### ISSUE THREAD

**Issue by johnrm9** [dwarvesf/hidden#178]
Instead of Command-Shift-P to call up preferences, why not use Command-comma (which is common practice).
Thanks.

**Comment by viettrungphan** [comment]
Because "cmd ;" only working when you open and focus on app window. With utility app, your app running in background, you need system global shortcut.

**Comment by johnrm9** [comment]
Yes. The command shortcut only works when Hidden menu is open and has focus. The Command-Shift-P key shortcut conflicts with VS Code to invoke the Command Pallet.  The  Command-comma for preference settings is common in applications. Pressing Command-Shift-P doesn't work as system global shortcut. I've tried it.
A very interesting app, Pareto Security uses Command-, for setting preferences. See https://github.com/ParetoSecurity/pareto-mac
Thanks

**Comment by viettrungphan** [comment]
In the app preferences you can set any shortcut that you like.
