### ISSUE TITLE
Feature Suggestion - Basic/Single Menu Bar Icon mode

### ISSUE THREAD

**Issue by OliverPearmain** [dwarvesf/hidden#184]
I personally always use Hidden Bar with the "line" to the immediate left of the "arrow"...

<img width="762" alt="Screenshot 2021-12-18 at 15 44 49" src="https://user-images.githubusercontent.com/765324/146646963-08f72e07-9a7f-4578-be2a-c24f2b048113.png">

It'd be great to have a mode where Hidden Bar just uses the "arrow" and anything to the left of it is collapsed/expanded when tapped.  This would give me more space when things are expanded and I wouldn't have to manage 2 menu bar icons. 

I think this'd give you three possible modes of operation:
- Single menu bar mode, with single "arrow" menu bar icon
- Default mode, with "line" and "arrow" menu bar icons 
- Always hidden mode, with 2x "line" and "arrow"  menu bar icons

Thanks for giving us great free software 🙏

**Comment by mcbaer** [comment]
You already have this, and you reported it as a bug, drag the line next to the arrow, right click the arrow to hide the "line".. anything to the left of the arrow is then hidden and there is no line..

**Comment by aroom** [comment]
> You already have this, and you reported it as a bug, drag the line next to the arrow, right click the arrow to hide the "line".. anything to the left of the arrow is then hidden and there is no line..

I don't think that you understood the feature request. The idea is that the arrow would act as the non transparent line. So when you click on it, you won't have the non transparent line taking place on the menu bar.

I would also appreciate such a feature. And also with the hidden mode (so juste one transparent bar for hidden icon, and the arrow for the rest)

**Comment by mcbaer** [comment]
> I don't think that you understood the feature request. The idea is that the arrow would act as the non transparent line. So when you click on it, you won't have the non transparent line taking place on the menu bar.


I think you don't understand how to use the app..

Drag the "non transparent" line all the way to the right, just to the left of the "arrow." **Right** Click the Arrow..

BOOM! The "non transparent" line is gone. 

When the "non transparent" line is gone (hidden) it doesn't take up any menubar space.. Then you just **left** click the arrow (or use hotkey) and you never see the "non transparent" line again.. 

Then you can drag things between the left side of the arrow, and the right side of the arrow.. like the line was never there..

**Comment by OliverPearmain** [comment]
@mB-PiBox just because the existing implementation of the app works for you doesn't mean that it does for all others, nor does it mean that their opinions are invalid. If you don't understand what's being requested here perhaps just move along instead of insulting those that do :-)

**Comment by mcbaer** [comment]
> @mB-PiBox just because the existing implementation of the app works for you doesn't mean that it does for all others, nor does it mean that their opinions are invalid. If you don't understand what's being requested here perhaps just move along instead of insulting those that do :-)

Because what you are requesting is already an option in the app..

> It'd be great to have a mode where Hidden Bar just uses the "arrow" and anything to the left of it is collapsed/expanded when tapped. 

I just explained how to do that.. as its already an option.. Hide the line by right clicking, and it will never be seen again until you right click the arrow again. There is no reason to have a specific option in the preferences for something that is already possible by just right clicking



And no one is insulting anyone. Please keep your estrogen induced snowflake crying to yourself. Telling someone they don't know how to use something, is not an insult. It's a statement

**Comment by viettrungphan** [comment]
If you read all the history you will know the reason we don't do it. We do it at the beginning of the production but Apple rejected our build. Finally we should add a separate bar to make it possible live in AppStore. Some people already asked same requests and we already told them why.
