### ISSUE TITLE
Could NOT hide icons in MacOS Mojave

### ISSUE THREAD

**Issue by shydow** [dwarvesf/hidden#19]
### Describe the bug

While I click icon, only | and > is hidden.

### Environment

You may write here the specifications like the version of the project, operating system, or hardware if applicable.

**Desktop (please complete the following information):**
 - OS: 10.14.4

**Comment by phucledien** [comment]
hi @shydow, sorry for the late answer.
Your problem sounds like you have used the tool wrong way.
Please follow the usage guide here [https://github.com/dwarvesf/hidden#usage](https://github.com/dwarvesf/hidden#usage)

**Comment by shydow** [comment]
> hi @shydow, sorry for the late answer.
> Your problem sounds like you have used the tool wrong way.
> Please follow the usage guide here https://github.com/dwarvesf/hidden#usage

Yes, It's works. Thanks
