### ISSUE TITLE
Hidden bar hides the date

### ISSUE THREAD

**Issue by TwinklyStar** [dwarvesf/hidden#218]
I need the date to stay on my menu bar all the time, but hidden bar hides it automatically. How can I leave the date shown on my menu bar?

**Comment by sergiotj** [comment]
@TwinklyStar here is the fix: https://github.com/dwarvesf/hidden/issues/207

**Comment by chusiang** [comment]
Thanks @sergiotj, I fixed this problem on my macOS v12.5.

1. Go to the **Docker & Menu Bar**.

    > Mac -> System Preferences... -> Docker & Menu Bar.

2. Scroll down and find **Clock**.
3. Change **Date options: Show date** to `always`, like this.

    ![2022-08-15menu-bar-clock](https://user-images.githubusercontent.com/219066/184644068-defc2dbe-47ac-4fc2-9733-0d43abf5dac6.png)

4. DONE.

    ![2022-08-15menu-bar-clock2](https://user-images.githubusercontent.com/219066/184644844-77d7d06c-1037-475e-aa64-4b2b15f295c8.png)
