### ISSUE TITLE
Do not auto hide icon after 5s when reopening the app

### ISSUE THREAD

**Issue by phucledien** [dwarvesf/hidden#22]
### Describe the bug
Do not auto-hide icon after 5s when reopening the app. 

### Steps to reproduce

1. Open Hidden bar the first time
2. Choose option auto-hide after 5s
3. Quit Hidden Bar
4. Reopen
5. Do not auto-hide

### Expected behavior
1. Open Hidden bar the first time
2. Choose option auto-hide after 5s
3. Quit Hidden Bar
4. Reopen
4. Auto-hide icon after 5s

### Environment

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.15.1

**Comment by viettrungphan** [comment]
Fixed
