### ISSUE TITLE
Add a Bartender-style sub-bar

### ISSUE THREAD

**Issue by giard-alexandre** [dwarvesf/hidden#234]
### Describe the bug

Adding a Bartender style sub-bar (see screenshot below) that is triggered using a button would be SUPER helpful, especially on Macs with the notch, which hides icons behind the notch (thanks Apple).

### Expected behaviour

Add a new context button that, when clicked, toggles the sub-bar visibility.
Optionally: clicking anywhere outside the bar closes it.

**Screenshots**

<img width="734" alt="image" src="https://user-images.githubusercontent.com/6423582/194085479-613af879-ae9d-47b0-ba73-51483975ee84.png">

**Comment by danielporto** [comment]
Came here to say this.
The number of apps just don't fit with the other application with a long list of menu options.
Allow to enable this with a keystroke too.
Currently, I am using Dozer, but I really wish to have a strong reason to switch.

**Comment by giard-alexandre** [comment]
Closing this issue as turns out it's a duplicate of #225 🙃

**Comment by ArneNostitz** [comment]
hi, any news on this or another way of pushing apps out from underneath the notch?
