### ISSUE TITLE
Can't access Preferences pane

### ISSUE THREAD

**Issue by anastaciaeg** [dwarvesf/hidden#244]
### Describe the bug

I don't seem to be able to get to the preferences pane anymore. I've tried quitting and relaunching the app, as well as right clicking on the menu bar icon, but the preferences pane will not appear or load, meaning I have no way to make adjustments to settings.

### Steps to reproduce

1. Go to the menu bar
2. Righ click on Collapse Icon (note that the Hidden Bar portion of the menu bar only seems to be particularly difficult to trigger a right click instead of a standard click)
3. The icon flashes briefly but no menu or window appears

### Expected behaviour

Upon right click, I get a menu with options to open the preferences pane or quit the app

### Environment

Mac OS Monterey 12.6.3 
2021 Macbook Pro with M1 Pro Chip

**Comment by tom-new** [comment]
You need to expand the hidden portion then right click on the pipe `|`, not on the caret `⟨`.

**Comment by anastaciaeg** [comment]
> You need to expand the hidden portion then right click on the pipe `|`, not on the caret `⟨`.

Perfect, thanks!
