### ISSUE TITLE
Update UI for preference window

### ISSUE THREAD

**Issue by phucledien** [dwarvesf/hidden#25]
I think we should add a gif instead of a static image for guiding user using the app.
![image](https://user-images.githubusercontent.com/14150687/70769201-210f2b00-1d9b-11ea-8d8d-ed088b463a9d.png)

**Comment by luckman212** [comment]
Thank you for this great and very lightweight app!

If you are making changes to the prefs dialog, can I suggest a few more minor things:

- "hold Command and drags icons" ==> "hold ⌘ and drag icons" (**drag**=singular)
- "Automatically hide icon after five seconds" ==> "Automatically hide icon**s** after 5 seconds" (**icons**=plural)
- fix double space between the words "Show" and "preferences"

**Comment by phucledien** [comment]
Thank you for the suggestions @luckman212, I'll definitely take a look at this
