### ISSUE TITLE
Is this app still maintained?

### ISSUE THREAD

**Issue by leoravagnani** [dwarvesf/hidden#251]
Every now and then I come to this repo to checkout if any improvements were made to the app and it seems the project has staled ): there's a bunch of issues open with interesting improvements (such as unifying icons) and bug reports (always hidden seems to not be working). Also there's some pretty straight forward PRs that could've been merged a good while ago... will this project be picked up again or should we as a community fork it and maintain it somewhere else?

I don't wanna come off as demanding because we all know this is free software and delivered as is, we're not paying customers. I just think this is a great tool that really improves the experience of using notch Macs and would like to see it getting better and better!!

**Comment by UeharaYou** [comment]
I forked this project and am working on rewriting it for better stability (PR #261). It will be great for you to come over and submit issues and PR.

**Comment by CollinsVakayil** [comment]
@leoravagnani @UeharaYou iBar on the AppStore is both completely free and kind of like Bartender and Hidden.

**Comment by dtruebin** [comment]
@leoravagnani, I believe the project maintainer answered your question in @UeharaYou's PR — https://github.com/dwarvesf/hidden/pull/261#issuecomment-1628355204:
> tbh, we don't think that we need any more changes with the latest version of Hidden Bar. And we do not have many resources for maintaining the hidden bar.
You can consider to fork hidden bar, and keep continue developing new features on that.

**Comment by leoravagnani** [comment]
@dtruebin yeah, since then I've been on @UeharaYou's fork 😸 

Oh btw I'm closing this issue. Here's the link to the fork for anyone looking for updates:
https://github.com/UeharaYou/HiddenBar
