### ISSUE TITLE
Login Item does not show up anywhere visible

### ISSUE THREAD

**Issue by luckman212** [dwarvesf/hidden#26]
When enabling the "Start when I log in" option, typically we should see a reference to the app in Login Items of System Preferences. However, in HiddenBar's case, this does not happen.

[Lingon X](https://www.peterborgapps.com/lingon/) fails to see it, as does [LaunchControl](https://www.soma-zone.com/LaunchControl/). Even `osascript -e 'tell application "System Events" to get the name of every login item'` from a bash shell does not list it. The only tool that I have found which enumerates the loginItem successfully is [KnockKnock](https://objective-see.com/products/knockknock.html).

Not sure if this is because of some nonstandard plist in the LauncherApplication.app bundle?

**Comment by phucledien** [comment]
Hi @luckman212, the API for adding the app to login items is now deprecated, so we are using this [API](https://developer.apple.com/documentation/servicemanagement/1501557-smloginitemsetenabled?language=objc) for launching the app after login.

You can see more here: https://developer.apple.com/documentation/coreservices/launch_services

**Comment by phucledien** [comment]
But I know that this feature does not work correctly sometimes. So we are trying to figure out the way to fix this problem. Any suggestions or PRs are welcome 👍

**Comment by L1cardo** [comment]
> out

I want to work on this!

**Comment by phucledien** [comment]
OK dude @L1cardo, feel free to work on this. Every contribution is worthy 🥇

**Comment by L1cardo** [comment]
@phucledien can I use cocoapods ?

**Comment by phucledien** [comment]
@L1cardo sr dude, but we want to not use dependencies as much as possible. We just use it, if it really waste us so many efforts for implementing it. And basically, I think this feature does not need to use dependency. :D

**Comment by L1cardo** [comment]
OK I will give it a shot

**Comment by L1cardo** [comment]
@phucledien What am I going to use is `Deprecated` in macOS 10.11, but this will work.
Is that OK ?

**Comment by phucledien** [comment]
Hm, I think you shouldn't use the deprecated at all, because I think they are deprecated for some reason. It would be better if you fix our current solution, or point out why it doesn't work sometimes. 🤔

**Comment by L1cardo** [comment]
The current method is not “not working”, but just invisible in the system preferences.
The current method is using an “applicationLauncher” to launch Hidden Bar. This can’t be seen in the system preferences 
I know a cocoapods library  that can’t let login item visible in system preferences, you could have a look.

**Comment by phucledien** [comment]
@L1cardo  ye, I took a look at it before. But because it using deprecated API so I don't want to use that. Hmm, what is the advantage of being in the login items, you think?

**Comment by L1cardo** [comment]
For me: 
- I can easily see what items automatically launch at login, and I can remove them without asking the permission of the App.
For the app: 
- it can make the size of App smaller (not having a launcher)
- it tells users that the App is not doing some dirty work in the background of your Mac (visible in system preferences)
- Old api (like you said, it uses an old api, so it may have problems in the future)


So, what to do is up to you. Or you can have a survey to know what others want.

**Comment by phucledien** [comment]
Ye, I totally agree with ur perspective 👍. But with me, using deprecated API is the thing I want to stay away from. So I think, we should stick with the current method.

**Comment by L1cardo** [comment]
Ok  agree with you

**Comment by phucledien** [comment]
So I will close this as there is no official way for doing this. Will reopen when Apple updates their API. Thank you guys 👍
