### ISSUE TITLE
Allow auto hide after X seconds to be configurable

### ISSUE THREAD

**Issue by aaronraimist** [dwarvesf/hidden#30]
### Describe the bug

I would like it to auto hide but five seconds is way too short for me especially since it can't detect if I am actively interacting with one of the icons. I would like the auto hide time period to be configurable.

**Comment by phucledien** [comment]
Thanks for the suggestion, we're working on this

**Comment by Moulde** [comment]
I agree, it would be nice if it did not hide when the user is interacting with some of the items to be hidden.

**Comment by viettrungphan** [comment]
Improved, just wait for our next release, we have 5 secs, 10 secs, 15 secs, 30 secs and one-minute options.
