### ISSUE TITLE
Global shortcut doesn't work when used with option or shift+option on macOS Sequoia

### ISSUE THREAD

**Issue by nkdm1** [dwarvesf/hidden#305]
### Describe the bug

When global shortcut is set to option+[letter] or shift+option+[letter] it doesn't work. Examples -> option+p, shift+option+p
It should expand the menu bar but it doesn't.
It works with command. Examples -> command+p, command+option+p, command+option+shift+p

### Steps to reproduce

1. Set the global shortcut to option+[letter] or shift+option+[letter].
2. Use the set shortcut to expand the menu bar.
3. See the bug.

### Expected behaviour

The set global shortcut should expand the menu bar.

**Screenshots**

Not really screenshot-able.

### Environment

The problem is macOS Sequoia specific, the shortcut worked on Sonoma.

**Desktop (please complete the following information):**
 - OS: macOS Sequoia.
 - Version: both 12 and 13.
 - Installed from: both brew and App Store installed apps don't work.

**Comment by matzegebbe** [comment]
https://developer.apple.com/forums//thread/763878?src=push&answerId=804374022#804374022

```
Frameworks Engineer
Apple

This was an intentional change in macOS Sequoia to limit the ability of key-logging malware to observe keys in other applications. The issue of concern was that shift+option can be used to generate alternate characters in passwords, such as Ø (shift-option-O).

There is no workaround; macOS Sequoia now requires that a hotkey registration use at least one modifier that is not shift or option.
```

**Comment by nkdm1** [comment]
I was able to found workaround to this problem. I used karabiner to map opt+p to cmd+opt+shift+p and set cmd+opt+shift+p to be a global shortcut, so my desired shortcut now works. Thanks for the reply :)

**Comment by matzegebbe** [comment]
@nkdm1 do you know why karabiner is allowed but this tool isn't? Is it because of the hotkey registration?

**Comment by nkdm1** [comment]
I have no idea unfortunately.
