### ISSUE TITLE
Enlarge clickable area for the "pipe" icon [enhancement]

### ISSUE THREAD

**Issue by bzx** [dwarvesf/hidden#33]
Very minor thing, but it would be nice if the clickable area for the "pipe" icon (which shows app's menu) is a bit larger, so that it's easier to click.

<img width="411" alt="Screenshot 2019-12-16 at 12 10 39" src="https://user-images.githubusercontent.com/654500/70902651-98dc9000-1ffd-11ea-931f-61fce386dcfe.png">

PS. Thanks for a great app! I've been using Vanilla which does the same thing but it was behaving funky sometimes, esp. when system theme changes. So far this looks promising, I will be testing this for the next few days!

**Comment by phucledien** [comment]
Thanks for using and giving us the suggestion @bzx, we'll update this in next release 👍

**Comment by viettrungphan** [comment]
@bzx thanks for your comment, we looked on Vanilla, the way they trick window cause some bugs when you are using multiple monitors or when you trigger Mission control, that is the reason why we build our own.
We will build more cool free Mac app. If you have any idea just let us know.

**Comment by phucledien** [comment]
Close this issue as the PR #42 solved this
