### ISSUE TITLE
Add it to home brew cask - please!

### ISSUE THREAD

**Issue by Fischmuetze** [dwarvesf/hidden#36]
Very nice app!!!
Would be great to have it in the home brew cask repositories! This give users the chance to automaticity the update process if they doesn't prefer the Apple App Store.

**Comment by phucledien** [comment]
ok dude, I will take time to look at it 👍

**Comment by djerfy** [comment]
It's available in HomeBrew Cask now :)

Install it with `brew cask install hiddenbar` :+1:

**Comment by phucledien** [comment]
close this as this was solved by @djerfy thanks bro <3
