### ISSUE TITLE
Using Label for localization instead of Image

### ISSUE THREAD

**Issue by viettrungphan** [dwarvesf/hidden#46]
We are using a separated image for each language.
- App size increased by adding more language.
- Hard for other people helping to translate because they don't have an image without text.

Solution:
- Using banner without text.
- Add 2 labels on top of the banner image.
- Localize text on labels.

**Comment by p-z-l** [comment]
Done.

**Comment by p-z-l** [comment]
I've proposed a new PR, check it out: [#50](https://github.com/dwarvesf/hidden/pull/50).
