### ISSUE TITLE
CLI to get the app version ?

### ISSUE THREAD

**Issue by rr0ss0rr** [dwarvesf/hidden#51]
I'm trying to automate the manual dmg download from git .. I can get the latest release from api.github.com and would like to query the release that's installed.  Is this possible?  I was hoping I could issue "/Applications/Hidden\ Bar.app/Contents/MacOS/Hidden\ Bar --version"

**Comment by luckman212** [comment]
You could always use something like
```
/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "/Applications/Hidden Bar.app/Contents/Info.plist" 2>/dev/null
```

**Comment by rr0ss0rr** [comment]
Ahh ... Works great ... Thanks

**Comment by phucledien** [comment]
I close this as this issue was solved, thanks @luckman212  👍
