### ISSUE TITLE
Displaying Preferences

### ISSUE THREAD

**Issue by rr0ss0rr** [dwarvesf/hidden#52]
If you choose "not to keep icon in dock" and "not show preferences at launch", then how would you get to the preferences?  Would it be possible to "option" click the menu icon?

**Comment by p-z-l** [comment]
Just simply left-click the separator icon, you will see a pop-up menu, select `Preferences...`; Or you can launch Hidden Bar again to get to Preferences Window.

<img width="822" alt="Screen Shot 2019-12-20 at 10 29 49 PM" src="https://user-images.githubusercontent.com/43706386/71261443-58bc3b00-2378-11ea-976b-91c179e09ce9.png">

**Comment by rr0ss0rr** [comment]
lol .. I thought it would be the <>

Thanks

**Comment by phucledien** [comment]
Haha,  here is the fun fact. At the first time, we used right-click at <> icon for showing an extra menu, but then Apple rejected the submit cause it doesn't follow an Apple guideline, so we switch to use the | icon =]

So I will close this as it's solved now.
