### ISSUE TITLE
App should allow removing itself from Dock

### ISSUE THREAD

**Issue by tieubao** [dwarvesf/hidden#54]
To keep the app completely hidden, I think we should allow users to run it as a faceless application or at least a menubar app (without an icon in the Dock). Check out below screenshots from Moom for reference

<img width="491" alt="Screen Shot 2019-12-22 at 8 59 39 PM" src="https://user-images.githubusercontent.com/1749624/71322784-0147d780-24fe-11ea-8def-127645b3228d.png">

<img width="499" alt="Screen Shot 2019-12-22 at 8 59 24 PM" src="https://user-images.githubusercontent.com/1749624/71322785-03aa3180-24fe-11ea-8d3f-213d745b0d46.png">

**Comment by p-z-l** [comment]
You can uncheck the "Keep Icon in Dock"  in the preferences window, therefore Hidden Bar won't display the icon in the Dock

**Comment by tieubao** [comment]
Found that option but just wonder if we can push it to another limit like faceless mode of Moom

**Comment by khit** [comment]
+1 for this request

Since the dock icon wouldn't be visible, right-clicking on Hidden Bar's < icon in the menu bar could allow access to Preferences, Quit, About, etc. That seems to be pretty standard among menu bar apps these days.

Thanks for creating this!

**Comment by p-z-l** [comment]
As viettrungphan mentioned in Issue #40:
> At the beginning of this project, we add only one button instead of 2 buttons (| and >) but Apple rejects our app because they don't let us use right mouse click on the bar button (the default left mouse click use to toggle show/hide). Finally, we end up with 2 buttons.

**Comment by khit** [comment]
Oh! I now see that you can right-click on the pipe "|" to get to Preferences & Quit the app already. Great news! That means we're more than half-way on this enhancement so I hope it is considered. Thanks again.

**Comment by p-z-l** [comment]
We didn't actually mean to do that, in macOS menu bar, left click & right click tends to be the same if developers do not specify the behavior.
