### ISSUE TITLE
Airplay icon position is reset to the right-most after some time

### ISSUE THREAD

**Issue by kn666** [dwarvesf/hidden#55]
### Describe the bug

Airplay icon position is not remembered and always reset to the right-most after some time

### Steps to reproduce

1. Drug airplay icon somewhere to the left in the hiding part
2. Wait
3. See airplay icon in the last position to the right of the hiding part

Originally I thought it's caused by reboot. But it survived reboot at least once. At the end of the day I find it going to the right.

### Expected behavior

airplay icon position should be preserved

**Desktop (please complete the following information):**
 - OS: 10.14.6
 - Version 1.3 (1)
MBP 2018

**Comment by phucledien** [comment]
hmm. I believe this is not our bug. It's the way Apple does stuff I think 🤔. And there is NO official way to adjust the status menu icon position programmatically.  So I think there is nothing we can do in this case. Anyway, I will let this issue open and wait for other ideas.

**Comment by kn666** [comment]
How cmd-drug manual icon reposition is handled? This is not a standard function of macos as I understand?

**Comment by phucledien** [comment]
cmd drag is a standard way for rearranging the status menu icon Apple giving to the end-user. And there is no OFFICIAL way for handling something like that programmatically. With the airplay case, I think they are using this private API for always making the icon on the right-most position.

`NSStatusItem *item = [NSStatusBar _statusItemWithLength:NSSquareStatusItemLength  withPriority:INT32_MAX];`

**Comment by kn666** [comment]
ok, thank you.
