### ISSUE TITLE
Error: Cask 'hiddenbar' is unavailable: No Cask with this name exists.

### ISSUE THREAD

**Issue by gwowg** [dwarvesf/hidden#58]
Error: Cask 'hiddenbar' is unavailable: No Cask with this name exists.

**Comment by phucledien** [comment]
Hello @gwowg, I rechecked and it works properly. So maybe you should run `brew update` before `brew cask install hiddenbar` 🤔

**Comment by phucledien** [comment]
close this as no response from @gwowg, feel free to reopen if you got any issue :D
