### ISSUE TITLE
Feature request or just some question

### ISSUE THREAD

**Issue by onewilk** [dwarvesf/hidden#59]
## First at all，nice work！I love it ❤

OK，here we go~
### Feature request or question list：

- show temporarily the icon of its state has update  (such as message unread count number has update）
- disable when the monitor screen is enough to show all icon
- hidden has two icon in status bar ,  has any impossible to hide one of them?

**Comment by p-z-l** [comment]
According to viettrungphan:
> At the beginning of this project, we add only one button instead of 2 buttons (| and >) but Apple rejects our app because they don't let us use right mouse click on the bar button (the default left mouse click use to toggle show/hide). Finally, we end up with 2 buttons.

----

The "show icons when they update" feature seems to be not very feasible for now. We use a very different method comparing with Bartender, hopefully we'll find a way to realize that.

----
"Disable when the monitor screen is enough to show all icon" feature seems to be a good idea, I'll try my best to work it out.

**Comment by onewilk** [comment]
Sorry for my poor english 😂

**Comment by p-z-l** [comment]
Doesn't matter, English is not my first language as well. 😂

**Comment by onewilk** [comment]
😂老铁，咱们还是中文交流吧。。。

**Comment by p-z-l** [comment]
哈哈哈。。这就很神奇了。。

**Comment by viettrungphan** [comment]
> ## First at all，nice work！I love it ❤
> OK，here we go~
> 
> ### Feature request or question list：
> * show temporarily the icon of its state has update  (such as message unread count number has update）
> * disable when the monitor screen is enough to show all icon
> * hidden has two icon in status bar ,  has any impossible to hide one of them?

"Disable when monitor screen is enough to show all icons" is the default behavior of MAC, this app targeted for users who want to hide some icons they don't like. 
"show temporarily the icon of its state has updated" Apple will not accept our update since it tracking other apps activities.

**Comment by m-cerveny** [comment]
> "show temporarily the icon of its state has updated" Apple will not accept our update since it tracking other apps activities.

This might be a stretch, but a non-MAS version (even paid) with pro features could be the way and a very welcome one...
