### ISSUE TITLE
Feature to show new added Icons or refreshed by default

### ISSUE THREAD

**Issue by Adrian-Grimm** [dwarvesf/hidden#61]
My main target ist to show my refreshing BitBar (Tool) Icons. But this should be an option in preferences for every new or refreshed Icon...

**Comment by m-cerveny** [comment]
This issue has 2 parts:

1. Refreshing icons - covered by #28 
2. Adding new (unknown to Hidden Bar so far) to the visible area

**Comment by phucledien** [comment]
@m-cerveny We cannot adjust the position of the menu bar item, at least with the public Apple API, I think 🤔. So part 2 is impossible to achieve. Btw thank you guys for the suggestions.

**Comment by viettrungphan** [comment]
This app not tracking or hold position of menu bar icons. The new or refreshing icon managed by the OS, you can try hold Command and drag you button around, as we know OS remember the buttons position when you rearrange them.

**Comment by Adrian-Grimm** [comment]
> @m-cerveny We cannot adjust the position of the menu bar item, at least with the public Apple API, I think 🤔. So part 2 is impossible to achieve. Btw thank you guys for the suggestions.

Bartender has a solution for this... but I don't know how they handle it. You can take a look on thier trail version.
