### ISSUE TITLE
Icons are covered by application menu elements

### ISSUE THREAD

**Issue by m-cerveny** [dwarvesf/hidden#62]
### Describe the bug

This seems to be the default behaviour of macOS menu bar. Will there be a possibility to improve on this? See screenshots of Safari and Calibre menu bars.

### Steps to reproduce

Just use an application with many menu items.

### Expected behaviour

Ideally, the icons would cover the menu items temporarily.

**Screenshots**
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/11475311/72336622-6a67d880-36c1-11ea-9cbc-2bd313dd48a5.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/11475311/72336636-75bb0400-36c1-11ea-8765-3f1276d27e8f.png">

### Environment

All macOS

**Comment by viettrungphan** [comment]
This is default Mac behavior. We can’t do anything with it.
