### ISSUE TITLE
There's too much space around the "<" button 

### ISSUE THREAD

**Issue by m-cerveny** [dwarvesf/hidden#63]
### Describe the bug

Menu bar precious space seems to be wasted with all that emptiness. See screenshot.

### Steps to reproduce

;)

### Expected behaviour

A bit less spacing might be a good idea...

**Screenshots**

<img width="131" alt="image" src="https://user-images.githubusercontent.com/11475311/72337571-178f2080-36c3-11ea-8bab-95c08dcc823d.png">

### Environment

all macOS

**Comment by phucledien** [comment]
Ok I see, we will resolve this problem in the next release. Thank you for your report 👍

**Comment by m-cerveny** [comment]
The same holds for the " | " separator button. I saw that there was a request to make the clickable area larger for " | " button, so probably something in the middle? ;)

**Comment by phucledien** [comment]
Close this as I did resolve in pr #64  ✊. Will be released in the next version. Thanks for your issue @m-cerveny.
