### ISSUE TITLE
Add hiding of Notification Center icon

### ISSUE THREAD

**Issue by maxwelljordanwhite** [dwarvesf/hidden#65]
This is the only thing holding it back for me, personally. Bartender does this, and it's nice, but only because I never touch Notification Center. Great application, though. I look forward to watching. :)

**Comment by p-z-l** [comment]
Unfortunately, Hidden Bar uses a significantly different way of hiding menu bar icons. We don't know how Bartender does this. So this feature may not be added in the near future.
