### ISSUE TITLE
Hard to see all the icons on a small screen

### ISSUE THREAD

**Issue by RedL0tus** [dwarvesf/hidden#77]
### Describe the bug

I'm a 13-inch MBP user. Hidden Bar is really a great project, it works perfectly during the most part of my usage. The only problem I met so far is that when I have over ~20 icons on the status bar, parts of them will be hidden; But those icons are shown on my secondary screen, which is 15.6-inch.

### Steps to reproduce

1. Open (many) softwares with tray icons
2. It will be like this on small screens (some of the icons are hidden):
![Status bar on a small screen](https://user-images.githubusercontent.com/16459559/78842442-d00fec00-79b4-11ea-9312-b7da51f84c02.png)
3. But on the larger screen, it looks like this:
![Status bar on a larger screen](https://user-images.githubusercontent.com/16459559/78842625-55939c00-79b5-11ea-9154-f2d6750d2d1e.png)

### Expected behaviour

Have some way to hide Safari's control menus from the status bar, or have some way to scroll through the tray icons.

### Environment

You may write here the specifications like the version of the project, operating system, or hardware if applicable.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Version: 1.5(9)

**Comment by viettrungphan** [comment]
This is the reason for HiddenBar was born. Hide icons you don't frequently use.

**Comment by RedL0tus** [comment]
> This is the reason for HiddenBar was born. Hide icons you don't frequently use.

But you cannot use some of the tray icons you hide, that is a problem. I don't think permanently hide some tray icons is a good design.

**Comment by RedL0tus** [comment]
> This is the reason for HiddenBar was born. Hide icons you don't frequently use.

Let's assume that I have 30 tray icons that I don't use, and also another that I have a strong urge to have access to. Those 30 useless icons are preventing me from accessing the one I need.

I met the similar problem that I have lost my access to newly opened Apps' tray icons.

What I want is to have some way to view all the hidden icons reliably.

**Comment by viettrungphan** [comment]
I understand your problem, however, this app uses to hide status bar icons, not the menu bar(button with text on the left-hand side). macOS set menu bar has high priority than the status bar when they don’t have enough space to display they will take space from the status bar. You can hold the Cmd button and drag status bar items you frequently use to the right-hand side to prevent it hide by not enough space.

I have a solution (but not sure it works because I did not try it yet, it comes from my other project ) to hide menu bar, however, it overkills and break simplifying theory of this app. If I have free time I will try to make that feature for you.

**Comment by RedL0tus** [comment]
> I understand your problem, however, this app uses to hide status bar icons, not the menu bar(button with text on the left-hand side). macOS set menu bar has high priority than the status bar when they don’t have enough space to display they will take space from the status bar. You can hold the Cmd button and drag status bar items you frequently use to the right-hand side to prevent it hide by not enough space.
> 
> I have a solution (but not sure it works because I did not try it yet, it comes from my other project ) to hide menu bar, however, it overkills and break simplifying theory of this app. If I have free time I will try to make that feature for you.

Thank you for your response. I understand it makes Hidden Bar more complicated, but it may be some sort of a "necessary evil" for users with smaller screens. Or is it possible to have some way to page the icons or scroll through all of them?

**Comment by cc978** [comment]
same questions. can not see the hidden icons, even the icons as too long menu of app or too many icons.
is it a way like Bartender showing the hidden icon in new line beneath or replace them in same line temporarily ??
see:
![image](https://user-images.githubusercontent.com/63266600/82248037-107e6480-997a-11ea-9de9-9c6067cf8222.png)
