### ISSUE TITLE
not work when use parallel desktop

### ISSUE THREAD

**Issue by lotosbin** [dwarvesf/hidden#78]
### Describe the bug

How does the program work in its current state? A clear and concise description of what you expected to happen.

### Expected behaviour

How do you think the program should work? Add screenshots and code blocks if necessary

**Screenshots**

### Environment

You may write here the specifications like the version of the project, operating system, or hardware if applicable.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

### Logs / Stack trace

```
Insert your log/stack trace here
```

**Comment by phucledien** [comment]
Hi @lotosbin, can you tell us more specifically about this issue 🤔 

It would be nice if there is any image, thank you 👍

**Comment by lotosbin** [comment]
@phucledien sorry, my mistake.
I moved '>' to left of '|', then it not works.
<img width="511" alt="Screen Shot 2020-04-24 at 15 44 33" src="https://user-images.githubusercontent.com/221294/80187611-8117b700-8642-11ea-8704-501a9a9e4e92.png">
