### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by rsv87** [dwarvesf/hidden#79]
Hello, 
I Love the App. I would just like to see if it would be possible to expand the apps where the  ">" is rather then at end of menu apps, in the scenario I would prefer to place ">" towards far right of the menu bar. I just fill having that would save even more time rather than having to move the cursor to the end of other menu apps.
Thank you for your attention.

**Comment by bartskowron** [comment]
You can move the “<“ icon to the right, next to Notification Center icon.
I don’t use the recent version of macOS but in previous versions it was possible to disable the Notification Center completely so the icon could be placed in the top right corner too ;)

**Comment by rsv87** [comment]
Yes you are correct you can move it, but my problem is that when you collapse the hidden apps by pressing the "<" they still collapse at the end of the menu extras rather than beside the now ">." My question/request is if there is a way to pin the collapsed apps, so when HiddenBar is collapsed they reveal themselves beside the ">" rather then automatically at the end.

**Comment by s-valent** [comment]
@rsv87 the idea is great and is how the app should be really implemented. However, not possible in the way the app is implemented.

**Comment by phucledien** [comment]
Hi @rsv87, sorry for the late response 😢 , as @s-valent mentioned, your idea is great and on the user side, I would also love it. But on the developer side, it's basically not able to accomplish because of the technical things.

Because of that, I have to close this issue. Sorry guys.
