### ISSUE TITLE
[Suggestion]: Use HiddenBar without "|".

### ISSUE THREAD

**Issue by SkyYkb** [dwarvesf/hidden#80]
## Expected Behavior:
Add an option that can use HiddenBar without "|" on the menu bar. And collapse icons on the left of ">" directly when click on it or press down shortcuts. Because "|" is also using the space on the menu bar.

**Comment by s-valent** [comment]
(I'm not a developer, I'm just passing by)

If I understand correctly, it is not as easy as it seems. Basically the app hides all the icons by making |'s size so large so it won't fit in menu bar. If you do that for for <, it will not simply show when it is resized.

I had a suggestion about another feature, so I slightly modified the app. Consider checking  [it](https://github.com/s-valent/hidden-bar), here you can change which part is hidden and then hide |.

**Comment by drasbeck** [comment]
I have not tried your fork, @s-valent, but kudos to you for implementing this. I'm thinking why not create a PR and let the maintainer decide whether or not to merge it?

**Comment by viettrungphan** [comment]
Accepted pull request. You can use it in latest version.
