### ISSUE TITLE
App (Bitbar) moves to hidden icon section

### ISSUE THREAD

**Issue by jvdmeij** [dwarvesf/hidden#81]
### Describe the bug

I am using Bitbar on my mac. Every time I open my Macbook, Bitbar is moved to the hidden icons section.

### Steps to reproduce

1. Install Bitbar
2. Move Bitbar to the visible icons section
3. Close you laptop, open it, log in
4. Bitbar is moved to the hidden icons section

### Expected behaviour

When I move an app/icon to the visible icons section, I expect it to always show up there.

Thanks!

**Comment by phucledien** [comment]
Hello, sorry for the late reply. This seems a Bitbar behavior, so we cannot do anything for now.

For more information about this, you can check [here](https://github.com/dwarvesf/hidden/issues/55)
