### ISSUE TITLE
"Display" menubar item gets unhidden after short time

### ISSUE THREAD

**Issue by mehlkopf** [dwarvesf/hidden#85]
### Describe the bug

I would like to hide the displays/Airplay/Sidecar menubar item. However, it's stubbornly re-appearing at its old spot just minutes after I dragged it into the hidden bar section and 100 % reproducible after every wake from sleep.

### Steps to reproduce

1. Enable "Show sync options …" in displays system preferences.
2. Drag it in the hidden bar section to hide it.
3. Wait a few minutes (or until the next wake from sleep), it will come back to the old non-hidden spot in the menubar.

### Expected behaviour

It should stay at its place in the hidden section.

### Environment
**MacBook Pro 2020**
 - OS: 10.15.5

**Comment by phucledien** [comment]
Hi @mehlkopf , thank you for raising the issue. 

This issue about misplacing of AirPlay menu icon has been known for awhile, and I really sorry to say that, this is a default behavior of AirPlay, and we can do nothing about that.

You can find more info [here](https://github.com/dwarvesf/hidden/issues/55)

**Comment by mehlkopf** [comment]
Oh, ok, thanks for letting me know!
