### ISSUE TITLE
Add a "toggle auto-hide" feature?

### ISSUE THREAD

**Issue by p-z-l** [dwarvesf/hidden#86]
I think it might be useful if the app can provide a "toggle auto-hide" option in the status menu. When the auto-hide is turned off, automatic hide icon timer will be temporarily disabled until the user turned the app on again.

If this is a good idea, I will start to work on this feature.

<br>

> *P.S. I did some testing, this app works perfect on Big Sur.*

**Comment by phucledien** [comment]
Hi @p-z-l , that idea sounds good to me. Feel free to implement it.
Can’t wait to see it👌

**Comment by p-z-l** [comment]
#87

**Comment by phucledien** [comment]
Close this.

I will release the new version soon 👍
