### ISSUE TITLE
Zoom menu bar returns to the hidden area on relaunch

### ISSUE THREAD

**Issue by asimen1** [dwarvesf/hidden#93]
### Describe the bug

Zoom menu bar returns to the hidden area on relaunch

### Steps to reproduce

1. Launch Zoom ([desktop client](https://zoom.us/download))
2. Make sure "Add Zoom to macOS menu bar" is turned on in settings->general
3. Move Zoom to the "shown" area
4. Quit Zoom
5. Launch Zoom

### Expected behaviour

Zoom menu bar should be in the "shown" area

### Environment

Version 1.6 (10)
 - OS: Catalina
 - Version 10.15.5

**Comment by phucledien** [comment]
Hi @asimen1 

I think this is Zoom's responsibility for remember its last position, so you should report this bug to Zoom instead.

Have a nice day 👍
