### ISSUE TITLE
Dropbox icon position is not stored

### ISSUE THREAD

**Issue by bxsx** [dwarvesf/hidden#94]
### Describe the bug

Every time I launch Dropbox its icon is in hidden section.
I know that while loading the icon first is greyed out, so I thought that maybe I need to reposition icon while loading Dropbox. Its the same. It doesn't matter if I move icon between | and > or on right from >. It stays there only until next relaunch.

### Environment

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.5.6 (the most recent)
 - HiddenBar: 1.6 (10)
 - Dropbox: 105.4.651 (I don't run Dropbox on startup, I launch it manually)

**Comment by bartskowron** [comment]
I noticed also Location Services icon provided by macOS doesn't keep the position. It is also going back to  the hidden section.
On the other hand AirPlay icon is always on the very right, next to the Notification Center. I can only guessing that this happens as the icon shows before HiddenBar is launched. Its usually very first icon on the status bar after restart to appear.

I have updated to macOS Catalina 10.5.7. The same behaviour.

**Comment by jabzzy** [comment]
same behavior for Docker Desktop and https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-

**Comment by bxsx** [comment]
Ah, I forgot about Docker Desktop, I have the same behaviour too.

**Comment by bxsx** [comment]
It's working fine since Docker Desktop v3.3.0

I'm closing it as seems like a problem in specific apps.

**Comment by jabzzy** [comment]
same problem can be reproduced with zoom.us too

maybe there's smth in common with these apps that hidden bar doesn't take into account?
