### ISSUE TITLE
图标在状态栏中的位置不能保存

### ISSUE THREAD

**Issue by hgaogao** [dwarvesf/hidden#96]
### Describe the bug

In mac os 11, the manually opened application will be hidden every time after booting, but before that, I have set that application to not hide, the software can’t remember whether my application is hidden

### Steps to reproduce

1. Open the application with the status bar icon
2. Set the application to display status
3. Close the application
4. Reopen

### Expected behaviour

The application should be displayed in the status bar, not hidden

**Screenshots**

![image](https://user-images.githubusercontent.com/47255125/93693497-1ad08b00-fb33-11ea-80de-d9e60c656b2e.png)

![image](https://user-images.githubusercontent.com/47255125/93693490-0ee4c900-fb33-11ea-986f-42a74203b593.png)

### Environment

mac os11 beta7
Hidden bar: 1.6 (10)
All applications

**Comment by yaohwu** [comment]
Same question on macOS Big Sur 11.0.1 20B29 x86_64

**Comment by viettrungphan** [comment]
Fixed in latest MacOS
