### ISSUE TITLE
For everyone would like to report the icons position bug on BigSur.

### ISSUE THREAD

**Issue by viettrungphan** [dwarvesf/hidden#98]
Look like BigSur changes the way the system manages app icons. The icon without assign '.autosaveName ' property will mess up.
I already fire the Feedback assistance to report the bug, I hope Apple will fix it soon, it related to the system, we can't do anything for now.
Thank you for reading and understanding.

**Comment by visini** [comment]
Thank you for your efforts! I also reported the issue to Apple. Looking forward to a fix.

**Comment by visini** [comment]
Seems to be resolved as of Version 11.1 Beta (20C5048k)

**Comment by viettrungphan** [comment]
I personally don't have this bug on M1 Macbook, don't know Apple fix it yet or not (on 11.0.1 (20B29))

**Comment by viettrungphan** [comment]
Fixed on latest MacOS.
